apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
 postgres-username: dXNlcm5hbWU=
 postgres-password: cGFzc3dvcmQ=
 database-url: cG9zdGdyZXM6Ly91c2VybmFtZTpwYXNzd29yZEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvc2ltcGxlcmVzdD9zc2xtb2RlPWRpc2FibGU=